name: Test install from crates.io

permissions:
  contents: read

on:
  push:
    paths:
      - ".github/workflows/install.yml"
  schedule:
    - cron: "17 0 * * 1"

jobs:
  cargo-install:
    strategy:
      matrix:
        locked: ["", "--locked"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: cargo-install
        run: |
          cargo install cargo-mutants ${{ matrix.locked }}
